elasticpoet:
  # build: 
  image: elasticsearch
  command: /bin/bash -c 'usermod -u 1000 elasticsearch; gosu elasticsearch elasticsearch'
  # environment:
  #   - 
  expose:
    - 9200
    - 9300
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - $PWD/esdata:/usr/share/elasticsearch/data
